// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3lvOkYzj2_reyfikBuv0m_WHU3zhkj1g',
    appId: '1:190353139949:web:7c1e85f01bf8fef9e704e4',
    messagingSenderId: '190353139949',
    projectId: 'farmsynchub',
    authDomain: 'farmsynchub.firebaseapp.com',
    storageBucket: 'farmsynchub.firebasestorage.app',
    measurementId: 'G-TTRBVSQ0EP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLX3lfPRKORpIcE-7i7DVMHnAANgPhuvw',
    appId: '1:190353139949:android:473d20925463c709e704e4',
    messagingSenderId: '190353139949',
    projectId: 'farmsynchub',
    storageBucket: 'farmsynchub.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-n6rQFAHR4CqScl1fuNDd98uj8TYSR6U',
    appId: '1:190353139949:ios:06a808beb78f6385e704e4',
    messagingSenderId: '190353139949',
    projectId: 'farmsynchub',
    storageBucket: 'farmsynchub.firebasestorage.app',
    iosClientId: '190353139949-h655366lmrfn2t8jr8rj24pkjsos2v9i.apps.googleusercontent.com',
    iosBundleId: 'com.farmsynchub.app',
  );

  // Firebase has no distinct "Windows" app type; Flutter's desktop plugins
  // talk to the same REST-style API as the Web SDK, so Windows uses its own
  // dedicated Web app registration (farmsynchub (windows), created via
  // `firebase apps:create WEB`) rather than throwing UnsupportedError.
  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3lvOkYzj2_reyfikBuv0m_WHU3zhkj1g',
    appId: '1:190353139949:web:fe60ad9a7a417d23e704e4',
    messagingSenderId: '190353139949',
    projectId: 'farmsynchub',
    authDomain: 'farmsynchub.firebaseapp.com',
    storageBucket: 'farmsynchub.firebasestorage.app',
    measurementId: 'G-TVCR3GPC2R',
  );
}
